sudo: false
group: deprecated-2017Q4
language: android
android:
  components:
    - extra-google-google_play_services
notifications:
  email: false
jdk:
  - oraclejdk8
  - openjdk7
before_install:
  - sed -i 's/<module>google-api-client-android<\/module>//'  pom.xml
  - sed -i 's/<module>google-api-client-assembly<\/module>//' pom.xml
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
