sudo: false
group: deprecated-2017Q4
language: android
android:
  components:
    - extra-google-google_play_services
notifications:
  email: false
jdk:
  - oraclejdk8
  - openjdk7
before_install:
  - mv .travis.pom.xml pom.xml
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
